### PR TITLE
support for ElasticSearch 2.2.0

### PR DESCRIPTION
**Pull request by bomberby**

### CODE REVIEW

**Comment by francesconero** [comment]
Should we add something to the readme to notify that this is for the 2.2.0 version of ES?

**Comment by bomberby** [comment]
As for the relevance of this specific branch to 2.2.0, it's probably obvious, but i'll add anyway.
Yes, the readme on master branch could use a reference to this branch, or even just copy the line about installation, but i'm not sure if this will work for versions beside 2.2.0 .
If needed, I can create branches per elastic version, as I've not been able to compile with support multiple  ES versions.

**Comment by francesconero** [comment]
Great, I'll update the master branch readme, maybe rename it to 1.X

**Comment by bomberby** [comment]
Thanks!

**Pull request merged**
